/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package worldserver3d.view;

import com.jme3.system.AppSettings;
import com.jme3.system.JmeCanvasContext;
import java.awt.BorderLayout;
import java.awt.Canvas;
import java.awt.Container;
import javax.swing.JMenu;
import javax.swing.JPanel;
import worldserver3d.WorldApplication;

/**
 *
 * @author gudwin
 */
public class WorldFrame extends javax.swing.JFrame {

    /**
     * Creates new form WorldFrame
     */
    
    public WorldFrame() {
        this(new WorldApplication());
    }
    
    public WorldFrame(WorldApplication wa) {
        initComponents();
        currentPanel = getContentPane();
        AppSettings settings = new AppSettings(true);
        settings.setWidth(1024);
        settings.setHeight(768);
        //app = new WorldApplication();
        app = wa;
        app.setPauseOnLostFocus(false);
        // This was included in my test
        settings.setResolution(1, 1);
        
        app.setSettings(settings);
        app.createCanvas();
        app.startCanvas();
        context = (JmeCanvasContext) app.getContext();
        canvas = context.getCanvas();
        canvas.setSize(settings.getWidth(), settings.getHeight());
        //this.setSize(settings.getWidth(), settings.getHeight());
        JPanel jp = new JPanel();
        jp.setLayout(new BorderLayout());
        //jp.setSize(settings.getWidth(), settings.getHeight());
        jp.add(canvas, BorderLayout.CENTER);
        setContentPane(jp);
        //currentPanel.add(jp,BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jFile = new javax.swing.JMenu();
        jNew = new javax.swing.JMenuItem();
        jOpen = new javax.swing.JMenuItem();
        JSave = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jExit = new javax.swing.JMenuItem();
        jOptions = new javax.swing.JMenu();
        scoreMenu = new javax.swing.JMenu();
        camMenu = new javax.swing.JMenu();
        createDeliverySpot = new javax.swing.JMenuItem();
        jRun = new javax.swing.JMenu();
        startTheGame = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WorldServer 3D - JME3 Edition");

        jFile.setText("File");

        jNew.setText("New");
        jNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNewActionPerformed(evt);
            }
        });
        jFile.add(jNew);

        jOpen.setText("Open");
        jOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOpenActionPerformed(evt);
            }
        });
        jFile.add(jOpen);

        JSave.setText("Save");
        JSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JSaveActionPerformed(evt);
            }
        });
        jFile.add(JSave);
        jFile.add(jSeparator1);

        jExit.setText("Exit");
        jExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitActionPerformed(evt);
            }
        });
        jFile.add(jExit);

        jMenuBar1.add(jFile);

        jOptions.setText("Options");

        scoreMenu.setText("Creatures Score");
        jOptions.add(scoreMenu);

        camMenu.setText("Creatures Cameras");
        jOptions.add(camMenu);

        createDeliverySpot.setText("Create Delivery Spot");
        createDeliverySpot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createDeliverySpotActionPerformed(evt);
            }
        });
        jOptions.add(createDeliverySpot);

        jMenuBar1.add(jOptions);

        jRun.setText("Run");

        startTheGame.setText("Start the Game");
        startTheGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startTheGameActionPerformed(evt);
            }
        });
        jRun.add(startTheGame);

        jMenuBar1.add(jRun);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 754, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 492, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNewActionPerformed
        // TODO add your handling code here:
        app.wap.newworld();
    }//GEN-LAST:event_jNewActionPerformed

    private void jExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitActionPerformed
        // TODO add your handling code here:
        app.stop();
        System.exit(0);
    }//GEN-LAST:event_jExitActionPerformed

    private void createDeliverySpotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createDeliverySpotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createDeliverySpotActionPerformed

    private void startTheGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startTheGameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startTheGameActionPerformed

    private void jOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOpenActionPerformed
        // TODO add your handling code here:
        app.wap.open();
    }//GEN-LAST:event_jOpenActionPerformed

    private void JSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JSaveActionPerformed
        // TODO add your handling code here:
        app.wap.save();
    }//GEN-LAST:event_JSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        WorldFrame wf = new WorldFrame();        
        wf.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JSave;
    private javax.swing.JMenu camMenu;
    private javax.swing.JMenuItem createDeliverySpot;
    private javax.swing.JMenuItem jExit;
    private javax.swing.JMenu jFile;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jNew;
    private javax.swing.JMenuItem jOpen;
    private javax.swing.JMenu jOptions;
    private javax.swing.JMenu jRun;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu scoreMenu;
    private javax.swing.JMenuItem startTheGame;
    // End of variables declaration//GEN-END:variables

    private JmeCanvasContext context;
    private Canvas canvas;
    private WorldApplication app;
    //private static JFrame frame;
    //private static Container canvasPanel1, canvasPanel2;
    private Container currentPanel;
    
    public JMenu getScoreMenu() {
        return(scoreMenu);
    }
    
    public JMenu getCamMenu() {
        return(camMenu);
    }
//public void createCanvas(){
//        
//    }


}
